const questions = [ {
    "1": "Explain High-performance computing and High-throughput computing. What are the design objectives to achieve High-performance computing and High-throughput computing? What are the applications of High-performance computing and High-throughput computing?",
    "2": "What are the three new computing paradigms? Define Centralized computing, Parallel computing, Distributed computing, Cloud Computing, Ubiquitous Computing, Internet Computing and Utility computing.",
    "3": "Discuss the different degrees of parallelism.",
    "4": "What is Internet of Things? What is Cyber physical system? Explain.",
    "5": "What is a computer cluster? Explain the architecture of cluster. What are the design issues in a cluster? What are the feasible implementations of various features of computer clusters?",
    "6": "What is grid computing? Explain with example.",
    "7": "What are peer-to-peer systems and overlay networks? Explain.",
    "8": "Explain the three different types of heterogeneity problems in hardware, software, and networks faced in P2P computing.",
    "9": "What is a cloud? What are internet clouds? Explain the three service models of cloud.",
    "10": "Explain service-oriented architecture. (or Explain the layered architecture for web services and grids.)",
    "11": "Discuss the evolution of service-oriented architecture.",
    "12": "Compare grids and clouds.",
    "13": "Compare the following features of Amoeba, DCE, and Mosix: History and current status, Distributed OS architecture, OS Kernel, Middleware and Virtualization support, Communication mechanisms.",
    "14": "Explain the concept of transparent computing environments for computing platforms.",
    "15": "Explain the different programming models for parallel and distributed computing.",
    "16": "What are the different performance metrics in distributed systems? Enumerate the dimensions of scalability characterized in parallel and distributed systems.",
    "17": "State Amdahl’s Law. What is the problem with fixed load? How can it be overcome?",
    "18": "Explain Gustafson’s law.",
    "19": "Explain system availability and application flexibility design goals in a distributed computing system.",
    "20": "Explain the different threats to systems and networks in cyberspace.",
    "21": "How can energy efficiency be achieved in different layers of distributed computing? Explain the dynamic power management and dynamic frequency voltage scaling methods incorporated into hardware systems.",
    "22": "Consider a multicore processor with four heterogeneous cores labelled A, B, C, and D... Compute the total execution time and calculate the processor utilization rate.",
    "23": "Consider a program for multiplying two large-scale N × N matrices... Answer questions related to speedup, efficiency, and implications.",
    "24": "What is a computer cluster? Explain its benefits.",
    "25": "Discuss the milestones of cluster systems.",
    "26": "What are design objectives of computer clusters? Explain.",
    "27": "Discuss the issues in cluster design.",
    "28": "Analyze the top 5 supercomputers.",
    "29": "Discuss the evolution of computer clusters and MPP architecture.",
    "30": "What are the categories of cluster nodes in an MPP system? Explain.",
    "31": "What are the different ways of cluster system interconnection? Discuss.",
    "32": "Discuss the hardware, software, and middleware support for SSI and HA in a cluster.",
    "33": "What are GPU clusters? How are they used for massive parallelism?",
    "34": "State and explain the design principles of computer clusters.",
    "35": "What is a single system image? What are its desired features?",
    "36": "Explain availability and failure rate.",
    "37": "Explain reliability, availability, and serviceability.",
    "38": "What are different redundancy techniques? What is isolated redundancy?",
    "39": "State and explain different fault-tolerant configurations.",
    "40": "Discuss the different checkpointing and recovery techniques.",  
    "41": "What are different cluster job scheduling methods? Explain.",
    "42": "Explain space sharing and time sharing.",
    "43": "What are the characteristics of cluster workload? Explain migration schemes.",
    "44": "What are the different levels of virtualization? Explain each in brief.",
    "45": "Discuss the requirements for Virtual Machine Monitor.",
    "46": "Compare the four VMM and Hypervisor Software Packages viz. VMWare Workstation, VMWare ESX Server, XEN and KVM.",
    "47": "Explain the virtualization at OS level. What are the advantages and disadvantages of OS extensions?",
    "48": "Explain the Xen architecture.",
    "49": "Explain full virtualization in detail.",
    "50": "Explain para-virtualization in detail.",
    "51": "What hardware supports virtualization? Discuss CPU virtualization and Hardware-assisted virtualization.",
    "52": "What is memory virtualization? Explain.",
    "53": "Discuss I/O virtualization.",
    "54": "Explain the functional blocks involved in sending and receiving network packets.",
    "55": "With the help of a diagram explain virtual hierarchy.",
    "56": "Compare physical versus virtual clusters.",
    "57": "What are the properties of provisioning of VMs to a virtual cluster dynamically? Explain the concept of a virtual cluster based on application partitioning.",
    "58": {
      "title": "Discuss the following with respect to virtual machine deployment:",
      "i": "Fast Deployment and Effective Scheduling",
      "ii": "High-Performance Virtual Storage"
    },
    "59": "What is live migration? Explain the live migration process in detail.",
    "60": "Explain the migration of memory, files and network resources.",
    "61": "What is server consolidation? Explain.",
    "62": "How is virtual storage managed? Discuss.",
    "63": "Give an overview of cloud operating systems for virtualized data centres.",
    "64": "How is virtual machine used for intrusion detection? Explain with an example.",
    "65": {
      "title": "What is Azure? Explain the following terminologies used in Azure:",
      "i": "Resource",
      "ii": "Subscription",
      "iii": "Azure Account",
      "iv": "Account Administrator",
      "v": "Region"
    },
    "66": {
      "title": "What is Azure? Explain the following terminologies used in Azure:",
      "i": "Microsoft Entra ID",
      "ii": "Microsoft Entra tenant",
      "iii": "Microsoft Entra Directory",
      "iv": "Resource Groups",
      "v": "Management Groups"
    },
    "67": "How does Azure work? Explain.",
    "68": "Give the classification of Azure services based on the cloud computing service model they leverage.",
    "69": "What are Azure foundational, mainstream, and strategic services?",
    "70": "Discuss the core Azure services in detail.",
    "71": "What are the advantages of the Azure Services?",
    "72": "Discuss the elements of hierarchy in Azure.",
    "73": "What resources can help to stay current with Azure? Explain.",
    "74": "What is Azure Resource Manager? What role does it play in handling Azure requests? Explain with a diagram.",
    "75": {
      "title": "Explain the following with respect to Azure Resource Manager:",
      "i": "Resource Provider",
      "ii": "Declarative Syntax",
      "iii": "ARM Template",
      "iv": "Bicep File",
      "v": "Extension Resource"
    },
    "76": "What is Azure Resource Manager? What can you do with resource manager?",
    "77": "Explain the four levels of management scope in Azure.",
    "78": "What is a resource group? What important factors should be considered while defining a resource group?",
    "79": "Why does resource group need location? Discuss the resiliency of Azure Resource Manager.",
    "80": "How does Azure Resource Manager resolve concurrent operations? What is Azure region?",
    
        "81": "Explain the different Azure management tools.",
        "82": {
          "title": "What is Azure Storage? What are its benefits? What are the data services offered by Azure Storage?"
        },
        "83": "Explain Azure Blob storage, Azure Files and Azure Elastic SAN.",
        "84": "Explain Azure Container Storage, Queue Storage, Table Storage, Disk Storage and Azure NetApp files.",
        "85": "What are the different authentication methods supported by Azure storage? Explain each in brief.",
        "86": "Explain the two types of encryption available for Azure Storage.",
        "87": {
          "title": "Discuss the following with respect to Azure storage:",
          "i": "Redundancy",
          "ii": "Transfer data to and from Azure Storage",
          "iii": "Pricing",
          "iv": "Storage APIs, library and tools"
        },
        "88": "Explain the Azure Network Architecture and its topology and components.",
        "89": "What is Azure virtual network? What should we use it? Explain.",
        "90": "What capabilities are provided by deploying services within a virtual network?",
        "91": "What are the different networking services provided by Azure? Explain in brief.",
        "92": {
          "title": "Explain the following with respect to Azure Networking:",
          "i": "Azure Virtual Network Manager",
          "ii": "ExpressRoute",
          "iii": "VPN Gateway",
          "iv": "Virtual WAN",
          "v": "Azure DNS"
        },
        "93": {
          "title": "Explain the following with respect to Azure Networking:",
          "i": "Azure Bastion",
          "ii": "NAT Gateway",
          "iii": "Route Server",
          "iv": "Peering Service"
        },
        "94": "What are the application protection services provided by Azure?",
        "95": "Explain the application delivery services provided by Azure.",
        "96": "What are the different network monitoring services provided by Azure? Explain each.",
        "97": "Discuss the features of Azure for network engineers.",
        "98": "What is Azure Application Gateway? Explain. What are its features?",
        "99": "Explain WebSocket and HTTP/2 traffic. What is connection draining?",
        "100": "Explain the steps to create Windows virtual machine on Azure portal.",
        "101": "Explain the Azure Virtual Machine baseline architecture.",
        "102": "Discuss the Virtual Machine design issues.",
        "103": {
          "title": "What is bootstrapping?",
          "i": "What are the common bootstrapping tasks?",
          "ii": "What are the recommendations for automation?"
        },
        "104": "Discuss the usage of disks to be attached to virtual machines mentioning the characteristics and performance expectations when selecting a disk.",
        "105": "Discuss the scaling strategies to prevent service level degradation and failures.",
        "106": {
          "title": "How can we change the size of the virtual machine?",
          "i": "What are the limitations?",
          "ii": "What is the workaround to overcome the limitations?"
        },
        "107": "Explain the subnetting considerations while setting up a virtual network in Azure.",
        "108": {
          "title": "What network controls should be applied to:",
          "i": "Ingress traffic",
          "ii": "Egress traffic",
          "iii": "East-west traffic",
          "iv": "Operational traffic",
          "v": "Private connectivity to PaaS services",
          "vi": "DDoS protection"
        },
        "109": "Discuss the monitoring of the data sources and collection aspects.",
        "110": "Discuss the monitoring of managed disks and applications.",
        "111": {
          "title": "Discuss the update management in Azure with respect to:",
          "i": "Infrastructure Updates",
          "ii": "OS images updates",
          "iii": "Guest OS patching"
        },
        "112": "How does Azure address reliability concerns?",
        "113": "Explain the scaling strategy in Azure for increasing reliability.",
        "114": "Discuss the security aspects in Azure.",
        "115": "How can we create a VM image from Azure Marketplace? Explain.",
        "116": "Explain the Secret Management architecture.",
        "117": "Discuss the cost optimization and recommendations for workload.",
        "118": {
          "title": "What is Azure Virtual Desktop?",
          "i": "What are its features?"
        }
      }
        
]
    
export default questions